#define ALARM_JSON_NAME "alarm"
#define MOTION_JSON_NAME "motion"
#define LIGHT_JSON_NAME "light"
#define FLAME_JSON_NAME "flame"
#define RGB_JSON_NAME "rgb"

#define SENSOR_NAME_JSON_NAME "name"
#define SENSOR_STATUS_JSON_NAME "enabled"
#define SENSOR_VALUE_JSON_NAME "value"
#define SENSOR_THRESHOLD_JSON_NAME "threshold"
#define STATUS_JSON_NAME "status"
#define SENSOR_READING_INTERVAL_JSON_NAME "interval"