#define ALARM_JSON_NAME "alarm"
#define TEMP_SENSOR_JSON_NAME "tempSensor"
#define VENT_ACTUATOR_JSON_NAME "ventActuator"
#define FLAME_SENSOR_JSON_NAME "flameSensor"

#define SENSOR_STATUS_JSON_NAME "enabled"
#define SENSOR_VALUE_JSON_NAME "value"
#define STATUS_JSON_NAME "status"
#define SENSOR_READING_INTERVAL_JSON_NAME "interval"
#define SENSOR_HIGH_THRESHOLD_JSON_NAME "highThreshold"
#define SENSOR_LOW_THRESHOLD_JSON_NAME "lowThreshold"
#define SENSOR_TEMP_TARGET_JSON_NAME "target"