#define ALARM_JSON_NAME "allarme"
#define MOTION_JSON_NAME "movimento"
#define LIGHT_JSON_NAME "luce"
#define FLAME_JSON_NAME "fiamma"
#define RGB_JSON_NAME "rgb"

#define SENSOR_NAME_JSON_NAME "nome"
#define SENSOR_STATUS_JSON_NAME "abilitato"
#define SENSOR_VALUE_JSON_NAME "misurazione"
#define SENSOR_THRESHOLD_JSON_NAME "soglia"
#define STATUS_JSON_NAME "stato"