#include <ArduinoJson.h>
/*
String createSingleHvacEditPage(JsonDocument doc) {
    JsonArray sensors = doc["sensors"].as<JsonArray>();
    JsonObject flameSensor;
    JsonObject tempSensor;
    JsonObject hvac;

    for(JsonVariant v : sensors){
      JsonObject obj = v.as<JsonObject>();
      if(obj[SENSOR_NAME_JSON_NAME] == TEMP_JSON_NAME){
         tempSensor = obj;
      } else if(obj[SENSOR_NAME_JSON_NAME] == FLAME_JSON_NAME){
        flameSensor = obj;
      }else if(obj[SENSOR_NAME_JSON_NAME] == HVAC_JSON_NAME){
        hvac = obj;
      }
    }
    JsonObject alarm = doc[ALARM_JSON_NAME].as<JsonObject>();


    String page = "<!doctype html>"
"<html lang='en'>"
"<head>"
"  <meta charset='utf-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1'>"
"  <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>"
"  <style>"
"    .form-group {"
"      margin-bottom: 1rem;"
"    }"
"    label {"
"      font-size: 1.25rem;"
"    }"
"    .sensor-group {"
"      border: 1px solid #dee2e6;"
"      padding: 15px;"
"      border-radius: 5px;"
"      margin-bottom: 20px;"
"    }"
"    .sensor-group h2 {"
"      margin-bottom: 20px;"
"    }"
"  </style>"
"  <title>Node: {{hvac.macAddress}}</title>"
"  <script>"
"      var currentLightValue = 125;"
"  </script>"
"</head>"
"<body>"
"  <div class='container py-5'>"
"    <h1 class='mb-5 text-center'>HVAC (" + String(doc["mac-address"]) + ")</h1>"
"    <h3 class='mb-5 text-center'>Status: " + String(doc["status"]) + "</h3>"
"    <form id='myForm' class='mx-auto'>"
"        <input type='hidden' value='" + String(doc["mac-address"]) + "' name='mac' id='mac' >"
"      <div class='row'>"
"        <div class='col'>"
"          <div class='sensor-group'>"
"            <h2>Flame Sensor</h2>"
"            <!-- Flame Sensor fields -->"
"            <div class='form-group'>"
"                <label for='flameIntervalSlider'>Light reading interval</label>"
"                <span id='flameIntervalSlider' class='d-block text-muted mb-2'>Current: " + String(flameSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "</span>"
"                <input type='range' class='form-control-range mb-3' id='flameIntervalSlider' name='flameIntervalSlider' min='1000' max='60000' step='250' value='"+ String(flameSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "'>"
"                <input type='number' class='form-control' id='flameIntervalSliderInput' name='flameIntervalSliderInput' min='1000' max='60000' step='250' value='"+ String(flameSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "'>"
"                <div class='invalid-feedback'>Please adjust the slider within the range of 1000 to 60000.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label>Status</label>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='flameStatus' id='flameEnabled' value='true'" + (flameSensor[SENSOR_STATUS_JSON_NAME] == true ? "checked" : "") + ">"
"                    <label class='form-check-label' for='flameEnabled'>Enabled</label>"
"                </div>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='flameStatus' id='flameDisabled' value='false'"+ (flameSensor[SENSOR_STATUS_JSON_NAME] == false ? "checked" : "") + ">"
"                    <label class='form-check-label' for='flameDisabled'>Disabled</label>"
"                </div>"
"                <div class='invalid-feedback'>Please select a status.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='flameDropdown'>Flame state</label>"
"                <select class='form-control' id='flameDropdown' name='flameDropdown'>"
"                    <option value='0'" + (flameSensor[STATUS_JSON_NAME] == 0 ? "selected" : "") + ">PRESENT</option>"
"                    <option value='1'" + (flameSensor[STATUS_JSON_NAME] == 1 ? "selected" : "") + ">ABSENT</option>"
"                </select>"
"                <div class='invalid-feedback'>Please select a choice from the dropdown.</div>"
"            </div>"
"        </div>"
"    </div>"
"    <div class='col'>"
"        <div class='sensor-group'>"
"            <h2>Temperature Sensor</h2>"
"            <!-- Temperature Sensor fields -->"
"            <div class='form-group'>"
"                <label for='targetTempSlider'>Target temperature</label>"
"                <span id='targetTempSliderValue' class='d-block text-muted mb-2'>Current: " + String(tempSensor[SENSOR_VALUE_JSON_NAME]) +"/" + String(tempSensor[SENSOR_TEMP_TARGET_JSON_NAME]) +"</span>"
"                <input type='range' class='form-control-range mb-3' id='targetTempSlider' name='targetTempSlider' min='15' max='35' value='"+ String(tempSensor[SENSOR_TEMP_TARGET_JSON_NAME]) + "'>"
"                <input type='number' class='form-control' id='targetTempSliderInput' name='targetTempSliderInput' min='15' max='35' value='"+ String(tempSensor[SENSOR_TEMP_TARGET_JSON_NAME]) + "'>"
"                <div class='invalid-feedback'>Please adjust the slider within the range of 15 to 35.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='highTempSlider'>High temperature threshold</label>"
"                <span id='highTempSliderValue' class='d-block text-muted mb-2'>Current: " + String(tempSensor[SENSOR_VALUE_JSON_NAME]) +"/" + String(tempSensor[SENSOR_HIGH_THRESHOLD_JSON_NAME]) +"</span>"
"                <input type='range' class='form-control-range mb-3' id='highTempSlider' name='highTempSlider' min='15' max='35' value='"+ String(tempSensor[SENSOR_HIGH_THRESHOLD_JSON_NAME]) + "'>"
"                <input type='number' class='form-control' id='highTempSliderInput' name='highTempSliderInput' min='15' max='35' value='"+ String(tempSensor[SENSOR_HIGH_THRESHOLD_JSON_NAME]) + "'>"
"                <div class='invalid-feedback'>Please adjust the slider within the range of 15 to 35.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='lowTempSlider'>Low temperature threshold</label>"
"                <span id='lowTempSliderValue' class='d-block text-muted mb-2'>Current: " + String(tempSensor[SENSOR_VALUE_JSON_NAME]) +"/" + String(tempSensor[SENSOR_LOW_THRESHOLD_JSON_NAME]) +"</span>"
"                <input type='range' class='form-control-range mb-3' id='lowTempSlider' name='lowTempSlider' min='15' max='35' value='"+ String(tempSensor[SENSOR_LOW_THRESHOLD_JSON_NAME]) + "'>"
"                <input type='number' class='form-control' id='lowTempSliderInput' name='lowTempSliderInput' min='15' max='35' value='"+ String(tempSensor[SENSOR_LOW_THRESHOLD_JSON_NAME]) + "'>"
"                <div class='invalid-feedback'>Please adjust the slider within the range of 15 to 35.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='tempIntervalSlider'>Temperature reading interval</label>"
"                <span id='tempIntervalSliderValue' class='d-block text-muted mb-2'>Current: " + String(tempSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "</span>"
"                <input type='range' class='form-control-range mb-3' id='tempIntervalSlider' name='tempIntervalSlider' min='10000' max='600000' step='10000' value='"+ String(tempSensor[SENSOR_READING_INTERVAL_JSON_NAME]) +"'>"
"                <input type='number' class='form-control' id='tempIntervalSliderInput' name='tempIntervalSliderInput' min='10000' max='600000' step='10000' value='"+ String(tempSensor[SENSOR_READING_INTERVAL_JSON_NAME]) +"'>"
"                <div class='invalid-feedback'>Please adjust the slider within the range of 10000 to 600000.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label>Status</label>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='tempStatus' id='tempEnabled' value='true'"+ (tempSensor[SENSOR_STATUS_JSON_NAME] == true ? "checked" : "") +">"
"                    <label class='form-check-label' for='tempEnabled'>Enabled</label>"
"                </div>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='tempStatus' id='tempDisabled' value='false'"+ (tempSensor[SENSOR_STATUS_JSON_NAME] == false ? "checked" : "") +">"
"                    <label class='form-check-label' for='tempDisabled'>Disabled</label>"
"                </div>"
"                <div class='invalid-feedback'>Please select a status.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='tempDropdown'>State</label>"
"                <select class='form-control' id='tempDropdown' name='tempDropdown'>"
"                    <option value='0'" + (tempSensor[STATUS_JSON_NAME] == 0 ? "selected" : "") + ">LOW</option>"
"                    <option value='1'" + (tempSensor[STATUS_JSON_NAME] == 1 ? "selected" : "") + ">NORMAL</option>"
"                    <option value='2'" + (tempSensor[STATUS_JSON_NAME] == 2 ? "selected" : "") + ">HIGH</option>"
"                </select>"
"                <div class='invalid-feedback'>Please select a choice from the dropdown.</div>"
"            </div>"
"        </div>"
"    </div>"
"    <div class='col'>"
"        <div class='sensor-group'>"
"            <h2>HVAC module</h2>"
"            <!-- Hvac Module fields -->"
"            <div class='form-group'>"
"                <label>Status</label>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='hvacStatus' id='hvacEnabled' value='true'"+ (hvac[SENSOR_STATUS_JSON_NAME] == true ? "checked" : "") +">"
"                    <label class='form-check-label' for='hvacEnabled'>Enabled</label>"
"                </div>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='hvacStatus' id='hvacDisabled' value='false'"+ (hvac[SENSOR_STATUS_JSON_NAME] == false ? "checked" : "") +">"
"                    <label class='form-check-label' for='hvacDisabled'>Disabled</label>"
"                </div>"
"                <div class='invalid-feedback'>Please select a status.</div>"
"            </div>"
"        </div>"
"    </div>"
"    <div class='col'>"
"        <div class='sensor-group'>"
"            <h2>ALARM</h2>"
"            <!-- ALARM fields -->"
"            <div class='form-group'>"
"                <label>The alarm is: </label>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='alarmStatus' id='alarmEnabled' value='true'"+ (alarm[SENSOR_STATUS_JSON_NAME] == true ? "checked" : "") +">"
"                    <label class='form-check-label' for='alarmEnabled'>Enabled</label>"
"                </div>"
"                <div class='form-check'>"
"                    <input class='form-check-input' type='radio' name='alarmStatus' id='alarmDisabled' value='false'"+ (alarm[SENSOR_STATUS_JSON_NAME] == false ? "checked" : "") +">"
"                    <label class='form-check-label' for='alarmDisabled'>Disabled</label>"
"                </div>"
"                <div class='invalid-feedback'>Please select a status.</div>"
"            </div>"
"            <div class='form-group'>"
"                <label for='alarmDropdown'>State</label>"
"                <select class='form-control' id='alarmDropdown' name='alarmDropdown'>"
"                    <option value='true'" + (alarm[STATUS_JSON_NAME] == true ? "selected" : "") + ">ACTIVE</option>"
"                    <option value='false'" + (alarm[STATUS_JSON_NAME] == false ? "selected" : "") + ">STANDBY</option>"
"                </select>"
"                <div class='invalid-feedback'>Please select a choice from the dropdown.</div>"
"            </div>"
"        </div>"
"    </div>"
"</div>"
"<div class='row'>"
"<button type='submit' class='btn btn-primary btn-block'>Submit</button>"
"</div>"
"</form>"
"</div>"
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js'></script>"
"<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>"
"<script>"
"    $(document).ready(function() {"
"        $('#targetTempSlider, #targetTempSliderInput').on('input', function() {"
"            var value = this.value;"
"            $('#' + this.id + 'Value').html('Current: " + String(tempSensor[SENSOR_VALUE_JSON_NAME]) + "/' + value);"
"            $('#' + this.id).val(value);"
"            $('#' + this.id + 'Input').val(value);"
"        });"
"        $('#tempIntervalSlider, #tempIntervalSliderInput').on('input', function() {"
"            var value = this.value;"
"            $('#' + this.id + 'Value').html('Current: " + String(tempSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "');"
"            $('#' + this.id).val(value);"
"            $('#' + this.id + 'Input').val(value);"
"        });"
"        $('#flameIntervalSlider, #flameIntervalSliderInput').on('input', function() {"
"            var value = this.value;"
"            $('#' + this.id + 'Value').html('Current: " + String(flameSensor[SENSOR_READING_INTERVAL_JSON_NAME]) + "');"
"            $('#' + this.id).val(value);"
"            $('#' + this.id + 'Input').val(value);"
"        });"
"        $('#myForm').on('submit', function(e) {"
"            e.preventDefault();"
"            var sliderValues = ['targetTempSliderInput' ];"
"            sliderValues.forEach(function(sliderValue) {"
"                var value = $('#' + sliderValue).val();"
"                if (value < 0 || value > 1000) {"
"                    $('#' + sliderValue).addClass('is-invalid');"
"                } else {"
"                    $('#' + sliderValue).removeClass('is-invalid');"
"                }"
"            });"
"            var radioValues = ['flameStatus', 'tempStatus', 'hvacStatus','alarmStatus'];"
""
"            radioValues.forEach(function(radioValue) {"
"                if (!$('input[name=\"' + radioValue +'\"]:checked').val()) {"
"                    $('input[name=\"' + radioValue +'\"]').addClass('is-invalid');"
"                } else {"
"                    $('input[name=\"' + radioValue +'\"]').removeClass('is-invalid');"
"                }"
"            });"
""            
"            var dropdDownValues = ['flameDropdown', 'tempDropdown', 'hvacDropdown','alarmDropdown'];"
""            
"            dropdDownValues.forEach(function(dropdown){"
"                if ($('#' + dropdown).val() == '') {"
"                    $('#' + dropdown).addClass('is-invalid');"
"                } else {"
"                    $('#' + dropdown).removeClass('is-invalid');"
"                }"
"            });"
"            if(!$('.is-invalid').length) {"
"                "
"                $.ajax({"
"    url: window.location.toString(),"
"    dataType: 'html',"
"    type:'put',"
"    contentType: 'application/x-www-form-urlencoded',"
"    data: $('#myForm').serialize() ,"
"    processData: false,"
"    success: function( data, textStatus, jQxhr ){"
"        alert('The new configuration has been sent to the device.');"
"    },"
"    error: function( jqXhr, textStatus, errorThrown ){"
"        alert('Error: ' + textStatus + '. ' + errorThrown );"
"    }"
"});"
"                            }"
"                        });"
"                    });"
"                </script>"
"                </body>"
"                </html>";
return page;
}
*/