#define ALARM_JSON_NAME "alarm"
#define MOTION_JSON_NAME "motion"
#define LIGHT_JSON_NAME "light"
#define FLAME_JSON_NAME "flame"
#define RGB_JSON_NAME "rgb"
#define HVAC_JSON_NAME "hvac"
#define TEMP_JSON_NAME "temp"

#define SENSOR_NAME_JSON_NAME "name"
#define SENSOR_STATUS_JSON_NAME "enabled"
#define SENSOR_VALUE_JSON_NAME "value"
#define STATUS_JSON_NAME "status"
#define SENSOR_READING_INTERVAL_JSON_NAME "interval"
#define SENSOR_HIGH_THRESHOLD_JSON_NAME "highThreshold"
#define SENSOR_LOW_THRESHOLD_JSON_NAME "lowThreshold"
#define SENSOR_TEMP_TARGET_JSON_NAME "target"